name: Deploy to VPS

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/audio-app
            git pull origin main

            # Update backend
            cd backend
            composer install --no-dev --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Update frontend
            cd ../frontend
            npm install
            npm run build
            pm2 restart frontend

            # Set permissions
            sudo chown -R apache:apache /var/www/audio-app
            sudo chmod -R 755 /var/www/audio-app
            sudo chmod -R 775 /var/www/audio-app/backend/storage

            echo "Deployment completed successfully!"
